### ISSUE TITLE
Bars have disappeared after upgrading to HA 0.113

### ISSUE THREAD

**Issue by rbluff** [custom-cards/bignumber-card#13]
Echoing what da_syygy reported here:
https://community.home-assistant.io/t/lovelace-bignumber-card/59280/42

Since upgrading to 0.113, and currently on 0.113.3, I no longer have coloured bars - only numbers.  

![image](https://user-images.githubusercontent.com/25833714/89745443-448ba080-daf7-11ea-9924-77746f341b6a.png)

da_syygy mentioned that it was related to themes, but I don't use any themes.

**Comment by anachronox99** [comment]
I have the same issue. Also, when I view this on an IoS device (just the default Safari browser) I get an error message. But when viewed on a desktop browser (I've tried Chrome and Edge Chromium) it renders correctly, just without the coloured bars. 
![MVIMG_20200810_131553](https://user-images.githubusercontent.com/16225843/89749639-f339dc00-db0b-11ea-9c57-fce0fd895734.jpg)

**Comment by nitobuendia** [comment]
Same issue. I troubleshooted a bit: background property is invalid.

Current value:
```css
        background: linear-gradient(
          to var(--bignumber-direction),
          var(--paper-card-background-color) var(--bignumber-percent),
          var(--bignumber-fill-color) var(--bignumber-percent)
        );
```

The structure is correct [direction], [color], [...n other colors]. However, I think --paper-card-background-color is not defined. This is more obvious because Chrome Developer tools usually highlights a square with the colour, but here, it doesn't (while it does for `var(--bignumber-fill-color)`).

After replacing this value with #FFFFFF, the bar started colouring again. Also, if changed to "transparent" seems to work.

<img width="597" alt="Screenshot 2020-08-10 at 19 19 13" src="https://user-images.githubusercontent.com/16522489/89777490-66f4dc80-db3e-11ea-9b8c-9429cc11f2a6.png">

In this image, the first one is #ffffff, the second one is transparent and the third `var(--paper-card-background-color)`.

I tracked down potential changes in the variable in frontend and it seems it was renamed on [this commit](https://github.com/home-assistant/frontend/pull/6377) from `paper-card-background-color` -> `card-background-color`. Changing for `var(--card-background-color)` also made it work:

<img width="593" alt="Screenshot 2020-08-10 at 19 23 31" src="https://user-images.githubusercontent.com/16522489/89777808-fe5a2f80-db3e-11ea-92c8-162fe0cdf3ab.png">

**Comment by nitobuendia** [comment]
I was about to send a Pull Request, but it seems #12 is doing something similar except using ha-background-color instead of --card-background-color.

**Comment by seventhsite** [comment]
Just installed it on last HA and there is no colored bars. Looks like module development is stopped. Is there any alternate modules for compact displaing instead of gauge?

**Comment by anachronox99** [comment]
Does anybody know if this component is still being developed?

**Comment by seventhsite** [comment]
> Does anybody know if this component is still being developed?

I installed code from Redame example and it is not work. Last update is 13 months ago. 
Looks like it is deprecated.

**Comment by ibennani** [comment]
An update was released the other day, and now my background colors are working again. 

New attribute: bncolor setts that background color.
